version: "3"

network:
  - saunalog

services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
        - ""
    networks:
      - saunalog
      - host
  
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086"
      - "8083"
      - "2003"
  networks:
    - saunalog
  volumes:
    - /srv/docker/influxdb/data:var/lib/influxdb
  deploy:
    placement:
      constraints: [node.role == manager]
    
  telegraf:
  image: telegraf:latest
  container_name: telegraf
  networks:
    - saunalog
  depends_on: influxdb
  volumes:
    - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on: 
      - influxdb
    ports:
      - "3000"
  networks:
    - saunalog
    - host
  volumes:
    - /srv/docker/grafana/data:var/lib/grafana
